//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptedTrade
    {
        public int TraderID { get; set; }
        public Nullable<int> Trader2ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> Job2ID { get; set; }
        public Nullable<bool> AcceptedT1 { get; set; }
        public Nullable<bool> AcceptedT2 { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Trader Trader { get; set; }
        public virtual Trader Trader1 { get; set; }
    }
}
