//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.AcceptedTrades = new HashSet<AcceptedTrade>();
        }
    
        public int ID { get; set; }
        public string Names { get; set; }
        public string Details { get; set; }
        public System.DateTime DueDate { get; set; }
        public int TraderID { get; set; }
        public int CategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcceptedTrade> AcceptedTrades { get; set; }
        public virtual Category Category { get; set; }
        public virtual Trader Trader { get; set; }
    }
}
