//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeSkill
    {
        public int TraderID { get; set; }
        public int CategoryID { get; set; }
        public string YearsOfExp { get; set; }
        public string ShortDes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Trader Trader { get; set; }
    }
}
